[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel", "gcc", "sqlite", "nodejs_20", "nodePackages.pnpm"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip", 
  "python -m pip install -r requirements.txt --no-cache-dir",
  "chmod +x setup_database.sh",
  "./setup_database.sh",
  "chmod +x update_api_endpoints.sh",
  "./update_api_endpoints.sh",
  "cd frontend && pnpm install && pnpm build && cd .."
]

[start]
cmd = "python direct_db_test.py"
