[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel", "gcc", "sqlite", "nodejs_20", "nodePackages.pnpm"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip", 
  "python -m pip install -r requirements.txt --no-cache-dir",
  "mkdir -p instance",
  "cp -f backend/instance/petrol_station.db instance/ || cp -f backend/petrol_station.db instance/ || echo 'Using existing database'",
  "chmod -R 777 instance || true",
  "chmod +x update_api_endpoints.sh",
  "./update_api_endpoints.sh",
  "cd frontend && pnpm install && pnpm build && cd .."
]

[start]
cmd = "chmod +x start.sh && ./start.sh"

# This tells Railway to persist the instance directory
[mount]
source = "sqlite_data"
destination = "/app/instance"
