[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel", "gcc", "sqlite", "nodejs_20", "nodePackages.pnpm"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip", 
  "python -m pip install -r requirements.txt --no-cache-dir",
  "echo '=== NIXPACKS DATABASE SETUP ==='",
  "ls -la backend/ || echo 'No backend directory'",
  "ls -la backend/instance/ || echo 'No backend/instance directory'",
  "mkdir -p instance",
  "if [ -f 'backend/instance/petrol_station.db' ]; then cp -f backend/instance/petrol_station.db instance/ && echo 'Database copied from backend/instance'; elif [ -f 'backend/petrol_station.db' ]; then cp -f backend/petrol_station.db instance/ && echo 'Database copied from backend'; else echo 'NO DATABASE FOUND TO COPY!'; fi",
  "chmod -R 777 instance || true",
  "chmod +x update_api_endpoints.sh",
  "./update_api_endpoints.sh",
  "cd frontend && pnpm install && pnpm build && cd .."
]

[start]
cmd = "chmod +x start.sh && ./start.sh"

# This tells Railway to persist the instance directory
[mount]
source = "sqlite_data"
destination = "/app/instance"
