[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel", "gcc"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip", 
  "python -m pip install -r backend/requirements.txt --no-cache-dir"
]

[variables]
PORT = "5000"

[start]
cmd = ["sh", "-c", "cd backend && python app.py"]
